### ISSUE TITLE
Understanding the role of Plugins in the Form::Tiny ecosystem

### ISSUE THREAD

**Issue by djerius** [bbrtj/perl-form-tiny#4]
I'm trying to understand how Plugins fit into the overall `Form::Tiny` ecosystem.

In particular, why would I use a plugin to apply a role or add methods when I can do that directly?

In other words, what advantage does

```
package My::Plugin;
use parent 'Form::Tiny::Plugin';
sub plugin { { roles => 'My::Role', subs => { foo => sub {...} } }

package My::Form;
use Form::Tiny plugins => [ '+My::Plugin' ]
...
```
have over
```
package My::Form;
use Form::Tiny;
with 'My::Role';
sub foo { ... }
```

Thanks!

**Comment by bbrtj** [comment]
Hey @djerius,

Plugin merging mechanisms cannot be 100% replaced with other means:
- meta roles cannot be easily added to the metaobject without the plugin system
- roles can be included with the `with` keyword as you shown, but including it in the plugin makes sure all roles will be consumed in one operation (which is the best practice)
- subs can be included just as a regular package subroutine, but doing so gives them different meaning. Subs included with the plugin are actually DSL keywords (like `form_field`) and have access to current field context (like `field_validator` does) through a scalar reference in a closure. If you use `namespace::autoclean`, all subs introduced via a plugin should be cleaned away from a package.

Other than that, having all three of those in the plugin system is just convenient :)

**Comment by bbrtj** [comment]
I have rewritten Form::Tiny::Plugin documentation to give better info about the purpose of plugins. It will be further improved after I resolve #7.

Don't hesitate to ask if you have more questions regarding plugins.

**Comment by djerius** [comment]
Thanks for the explanation (and your patience!).  I didn't fully understand the role `$context` played.

To revive this old thread,  I've run into a situation where it would be nice to automatically load DSL commands from a meta rule.

I have a number of roles which rely upon DSL keywords to supply necessary information. 
Currently my Plugin.pm file looks like this:
```
package App::CXC::acis_empsf::Validate::Plugin;

use App::CXC::acis_empsf::Base;

use parent 'Form::Tiny::Plugin';

sub plugin ( $self, $caller, $context ) {
    return {
        roles => [
            "${\APP_BASE}::Validate::FormTiny::Config",
            "${\APP_BASE}::Validate::FormTiny::Class",
            "${\APP_BASE}::Validate::FormTiny::Options::OptArgs",
        ],
        meta_roles => [
            "${\APP_BASE}::Validate::FormTiny::Options::OptArgsMeta",
            "${\APP_BASE}::Validate::FormTiny::FormMeta",
            "${\APP_BASE}::Validate::FormTiny::Class::MooMeta",
            "${\APP_BASE}::Validate::FormTiny::ConfigMeta",
            "${\APP_BASE}::Validate::FormTiny::WrapBlueprint",
        ],
        subs => {
            config_path => sub ( @path ) {
                $caller->form_meta->_dsl_config_path( $context->$*, @path );
            },

            option => sub ( $hash ) {
                $caller->form_meta->_dsl_add_option( $context->$*, $hash );
            },

            argument => sub ( $hash ) {
                $caller->form_meta->_dsl_add_argument( $context->$*, $hash );
            },
        },

    };
}
```
Eventually I'll be using them in other applications, so rather than having to explicitly create the DSL commands `config_path`, `option`, and `argument`, it'd be less error prone to have them automatically added when their associated meta roles (`ConfigMeta` and `Options::OptArgsMeta`) are loaded.

**Comment by bbrtj** [comment]
Well yes, If all your DSL commands do is call meta methods, then it is a bit of repetition. But that's just the way the entire system is bootstrapped. To do this sort of thing automatically, it would have to inspect available methods and create subs for methods with a prefix, like in your case. I think that's more hassle than it's worth.

If you want to reduce boilerplate, generating them yourself should not be very hard:

```
for my $sub_name (qw(config_path option argument)) {
  $subs{$sub_name} = sub {
    my $method_name = "_dsl_add_$sub_name";
    $caller->form_meta->$method_name($context->$*, @_);
  };
}
```

You can move this code to some utils package and reuse. Note: your `config_path` DSL does not call a method that starts with `_dsl_add_`.
