### ISSUE TITLE
Tests are failing when perl is compiled with -Dusequadmath

### ISSUE THREAD

**Issue by andk** [bbrtj/perl-form-tiny#5]
Sample fail report: http://www.cpantesters.org/cpan/report/9f63e6ce-12f0-11ed-93b9-9b7c797b756e

**Comment by bbrtj** [comment]
This is most likely a Type::Tiny bug.

Type::Tiny started failing with quadmath as well: http://www.cpantesters.org/cpan/report/63f0927e-144c-11ed-a386-da3e94459d83

Types::Standard::Int seems to think floats are OK. Most likely needs reporting in Type::Tiny, but better to wait for more quadmath failures there. Will keep this open for now.

**Comment by bbrtj** [comment]
Confirmed as Type::Tiny bug by Toby, closing.
