### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by djerius** [bbrtj/perl-form-tiny#9]
In Form::Tiny::Manual,

(arbitrary line numbers)
 
     1	   use Data::Dumper;
     2	   my $form = SomeForm->new;
     3	
     4	   $form->set_input({
     5	           name => 'perl',
     6	           lucky_number => 6,
     7	   });
     8	
     9	   if ($input->valid) {
    10	           print Dumper $form->fields;
    11	   }
    12	   else {
    13	           print Dumper $form->errors;
    14	           print Dumper $form->errors_hash;

line 9  should be

     9	   if ($form->valid) {

**Comment by bbrtj** [comment]
Yes, good catch. Would you fancy submitting a patch for this?

**Comment by bbrtj** [comment]
Resolved in #10
